pipeline {
    agent any

    tools {
        maven 'Maven 3'  // Usa el nombre que configuraste para Maven en Jenkins
    }

    environment {
        SONAR_TOKEN = credentials('sonar-token')  // Asegúrate de tener configurada esta credencial en Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify POM') {
            steps {
                script {
                    // Verifica que el archivo pom.xml está en el directorio correcto
                    sh 'ls -la'
                }
            }
        }

        stage('Build with Maven') {
            steps {
                script {
                    // Ejecuta el comando de Maven para construir el proyecto
                    sh 'mvn clean install'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    // Realiza el análisis con SonarQube
                    withSonarQubeEnv('SonarQube-Local') {
                        sh 'mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN'
                    }
                }
            }
        }
    }

    post {
        success {
            echo '¡El análisis y construcción fueron exitosos!'
        }

        failure {
            echo '¡Hubo un error durante la construcción o el análisis!'
        }
    }
}











